name: Android APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Gradle Permission
      - name: Grant execute permission
        run: chmod +x gradlew

      # Download ONNX Model
      - name: Download ONNX Model
        run: |
          mkdir -p app/src/main/assets
          curl -L \
            -o app/src/main/assets/model.onnx \
            https://github.com/shotcrete/myanmartts-app/raw/main/app/src/main/assets/model.onnx

      # Delete English Model
      - name: Remove English Model
        run: |
          rm -f app/src/main/assets/en_model.onnx
          rm -f app/src/main/assets/en_model.onnx.json

      # Clean
      - name: Clean Project
        run: ./gradlew clean

      # Build APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Release
      - name: Upload APK Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Build #${{ github.run_number }}
          prerelease: true
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Telegram
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Build Success

            APK:
            https://github.com/${{ github.repository }}/releases/download/build-${{ github.run_number }}/app-debug.apk
